"use server";
import{createClient}from"@/lib/supabase/server";import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import type{MediaItem,Spec,QA}from"@/lib/types";

function requiredClient(){const s=createClient();if(!s)throw new Error("Connect Supabase in .env.local first.");return s}
function lines(value:FormDataEntryValue|null){return String(value||"").split("\n").map(x=>x.trim()).filter(Boolean)}
function pairs(value:FormDataEntryValue|null):Spec[]{return lines(value).map(x=>{const[a,...b]=x.split("|");return{label:a.trim(),value:b.join("|").trim()}}).filter(x=>x.label&&x.value)}
function faqs(value:FormDataEntryValue|null):QA[]{return lines(value).map(x=>{const[q,...a]=x.split("|");return{question:q.trim(),answer:a.join("|").trim()}}).filter(x=>x.question&&x.answer)}
function slugify(s:string){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
async function uploadFiles(form:FormData,field="media"){const s=requiredClient();const files=form.getAll(field).filter(x=>x instanceof File&&x.size>0)as File[];const out:MediaItem[]=[];for(const file of files){const ext=file.name.split(".").pop();const path=`${new Date().getFullYear()}/${crypto.randomUUID()}.${ext}`;const{error}=await s.storage.from("media").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const{data}=s.storage.from("media").getPublicUrl(path);out.push({type:file.type.startsWith("video/")?"video":"image",url:data.publicUrl,alt:file.name})}return out}
function productPayload(form:FormData,media:MediaItem[]){const name=String(form.get("name")||""),model=String(form.get("model")||"");return{name,model,slug:String(form.get("slug")||slugify(model||name)),category:String(form.get("category")||"Other"),subcategory:String(form.get("subcategory")||""),short_description:String(form.get("short_description")||""),description:String(form.get("description")||""),features:lines(form.get("features")),specifications:pairs(form.get("specifications")),packing_size:pairs(form.get("packing_size")),parts_list:lines(form.get("parts_list")),faqs:faqs(form.get("faqs")),applications:lines(form.get("applications")),customization:lines(form.get("customization")),media,youtube_url:String(form.get("youtube_url")||""),datasheet_url:String(form.get("datasheet_url")||""),seo:{title:String(form.get("seo_title")||""),description:String(form.get("seo_description")||""),keywords:String(form.get("seo_keywords")||""),canonical:String(form.get("canonical")||"")},ai_summary:String(form.get("ai_summary")||""),moq:String(form.get("moq")||""),featured:form.get("featured")==="on",status:String(form.get("status")||"draft"),sort_order:Number(form.get("sort_order")||0)}}

async function orderedProductMedia(form:FormData,existing:MediaItem[]=[]){const s=requiredClient(),uploaded=new Map<string,MediaItem>(),order=String(form.get("media_order")||"").split(",").filter(Boolean);async function upload(token:string,file:File){if(!order.includes(token)||!file.size)return;const ext=file.name.split(".").pop(),path=`${new Date().getFullYear()}/${crypto.randomUUID()}.${ext}`;const{error}=await s.storage.from("media").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const{data}=s.storage.from("media").getPublicUrl(path);uploaded.set(token,{type:file.type.startsWith("video/")?"video":"image",url:data.publicUrl,alt:file.name})}for(const[token,value]of form.entries())if(token.startsWith("media_n")&&value instanceof File)await upload(token.replace("media_",""),value);const batch=form.getAll("media_batch").filter(value=>value instanceof File&&value.size>0)as File[];for(let index=0;index<batch.length;index++)await upload(`b${index}`,batch[index]);const media:MediaItem[]=[];for(const token of order){if(token.startsWith("e")){const index=Number(token.slice(1));if(form.get(`delete_media_${index}`)!=="on"&&existing[index])media.push(existing[index])}else if(uploaded.has(token))media.push(uploaded.get(token)!)}return media.slice(0,8)}

export async function createProduct(form:FormData){const s=requiredClient();const media=await orderedProductMedia(form);const{error}=await s.from("products").insert(productPayload(form,media));if(error)throw error;revalidatePath("/products");redirect("/admin/products")}
export async function updateProduct(id:string,existing:MediaItem[],form:FormData){const s=requiredClient();const media=await orderedProductMedia(form,existing);const{error}=await s.from("products").update(productPayload(form,media)).eq("id",id);if(error)throw error;revalidatePath("/products");redirect("/admin/products")}
export async function deleteProduct(id:string){const s=requiredClient();await s.from("products").delete().eq("id",id);revalidatePath("/products")}
export async function createCategory(form:FormData){const s=requiredClient();const name=String(form.get("name")||"").trim();if(!name)throw new Error("Category name is required.");const payload={name,slug:String(form.get("slug")||slugify(name)),description:String(form.get("description")||""),sort_order:Number(form.get("sort_order")||0),published:form.get("published")==="on"};const{error}=await s.from("product_categories").insert(payload);if(error)throw error;revalidatePath("/products");revalidatePath("/");redirect("/admin/categories")}
export async function updateCategory(id:string,form:FormData){const s=requiredClient();const name=String(form.get("name")||"").trim();if(!name)throw new Error("Category name is required.");const payload={name,slug:String(form.get("slug")||slugify(name)),description:String(form.get("description")||""),sort_order:Number(form.get("sort_order")||0),published:form.get("published")==="on"};const{error}=await s.from("product_categories").update(payload).eq("id",id);if(error)throw error;revalidatePath("/products");revalidatePath("/");redirect("/admin/categories")}
export async function deleteCategory(id:string){const s=requiredClient();const{error}=await s.from("product_categories").delete().eq("id",id);if(error)throw error;revalidatePath("/products");revalidatePath("/")}
export async function savePage(slug:string,existing:MediaItem[],form:FormData){const s=requiredClient();const fresh=await uploadFiles(form);const keep=existing.filter((_,i)=>form.get(`delete_page_media_${i}`)!=="on");const media=[...keep,...fresh].slice(0,12);const payload={slug,title:String(form.get("title")||slug),eyebrow:String(form.get("eyebrow")||""),heading:String(form.get("heading")||""),body:String(form.get("body")||""),content:{video_url:form.get("delete_external_video")==="on"?"":String(form.get("video_url")||""),cta_label:String(form.get("cta_label")||"Request a Quote"),cta_url:String(form.get("cta_url")||"/contact"),catalog_label:String(form.get("catalog_label")||"Download Catalog"),catalog_url:String(form.get("catalog_url")||""),...Object.fromEntries([1,2,3,4].flatMap(i=>[[`stat_value_${i}`,String(form.get(`stat_value_${i}`)||"")],[`stat_label_${i}`,String(form.get(`stat_label_${i}`)||"")]])),partner_kicker:String(form.get("partner_kicker")||"Trusted by"),partner_title:String(form.get("partner_title")||"Partner"),partner_accent:String(form.get("partner_accent")||"Brands"),partner_description:String(form.get("partner_description")||"Selected customer and partner logos."),why_title:String(form.get("why_title")||"Why Partner"),why_accent:String(form.get("why_accent")||"With Us"),why_description:String(form.get("why_description")||"From prototype to mass production, we deliver reliable support at every stage"),...Object.fromEntries([1,2,3,4].flatMap(i=>[[`why_card_title_${i}`,String(form.get(`why_card_title_${i}`)||"")],[`why_card_body_${i}`,String(form.get(`why_card_body_${i}`)||"")]])),sections:[1,2,3,4,5].map(i=>({title:String(form.get(`section_title_${i}`)||""),body:String(form.get(`section_body_${i}`)||"")}))},media,published:form.get("published")==="on"};const{error}=await s.from("pages").upsert(payload);if(error)throw error;revalidatePath(`/${slug==="home"?"":slug}`);redirect("/admin/content")}
export async function addGalleryItem(form:FormData){const s=requiredClient();const uploaded=await uploadFiles(form);const media=uploaded[0];if(!media)throw new Error("Choose an image or video.");const collection=String(form.get("collection"));const{error}=await s.from("site_media").insert({collection,title:String(form.get("title")),caption:String(form.get("caption")||""),media_type:media.type,media_url:media.url,link_url:String(form.get("link_url")||""),sort_order:Number(form.get("sort_order")||0),published:form.get("published")==="on"});if(error)throw error;revalidatePath("/");revalidatePath("/scenes");const returnTo=String(form.get("return_to")||"/admin/media");redirect(returnTo.startsWith("/admin/")?returnTo:"/admin/media")}
export async function deleteGalleryItem(id:string){const s=requiredClient();await s.from("site_media").delete().eq("id",id);revalidatePath("/");revalidatePath("/scenes")}
export async function uploadCatalog(form:FormData){const s=requiredClient();const file=form.get("catalog");if(!(file instanceof File)||file.size===0||file.type!=="application/pdf")throw new Error("Choose a PDF catalog.");const path=`catalog/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error:uploadError}=await s.storage.from("media").upload(path,file,{contentType:"application/pdf",upsert:false});if(uploadError)throw uploadError;const{data}=s.storage.from("media").getPublicUrl(path);await s.from("site_media").update({published:false}).eq("collection","catalog");const{error}=await s.from("site_media").insert({collection:"catalog",title:String(form.get("title")||file.name),caption:String(form.get("version")||""),media_type:"document",media_url:data.publicUrl,sort_order:0,published:true});if(error)throw error;revalidatePath("/");redirect("/admin/catalog")}
export async function saveNews(form:FormData){const s=requiredClient();const uploaded=await uploadFiles(form,"cover");const title=String(form.get("title")||"");const payload={title,slug:String(form.get("slug")||slugify(title)),excerpt:String(form.get("excerpt")||""),content:String(form.get("content")||""),category:String(form.get("category")||"Company"),cover_url:uploaded[0]?.url||String(form.get("existing_cover")||""),published_at:String(form.get("published_at")||new Date().toISOString().slice(0,10)),status:String(form.get("status")||"draft")};const id=String(form.get("id")||"");const q=id?s.from("news").update(payload).eq("id",id):s.from("news").insert(payload);const{error}=await q;if(error)throw error;revalidatePath("/news");redirect("/admin/news")}
export async function deleteNews(id:string){const s=requiredClient();await s.from("news").delete().eq("id",id);revalidatePath("/news")}
export async function saveQuote(form:FormData){const s=requiredClient();const payload={quote_no:String(form.get("quote_no")),customer:String(form.get("customer")),product:String(form.get("product")),currency:String(form.get("currency")||"USD"),unit_price:Number(form.get("unit_price")||0),moq:Number(form.get("moq")||0),lead_time:String(form.get("lead_time")||""),packing_size:{product_size:String(form.get("product_size")||""),package_size:String(form.get("package_size")||""),net_weight:String(form.get("net_weight")||""),gross_weight:String(form.get("gross_weight")||""),qty_carton:String(form.get("qty_carton")||""),carton_size:String(form.get("carton_size")||""),carton_nw:String(form.get("carton_nw")||""),carton_gw:String(form.get("carton_gw")||""),cbm:String(form.get("cbm")||"")},notes:String(form.get("notes")||"")};const{error}=await s.from("quotes").insert(payload);if(error)throw error;redirect("/admin/quotes")}
export async function deleteQuote(id:string){const s=requiredClient();const{error}=await s.from("quotes").delete().eq("id",id);if(error)throw error;revalidatePath("/admin/quotes")}
export async function saveContentEntry(form:FormData){const s=requiredClient();const uploaded=await uploadFiles(form,"cover");const title=String(form.get("title")||"");const payload={type:String(form.get("type")||"article"),slug:String(form.get("slug")||slugify(title)),title,excerpt:String(form.get("excerpt")||""),content:String(form.get("content")||""),category:String(form.get("category")||""),cover_url:uploaded[0]?.url||String(form.get("existing_cover")||""),faqs:faqs(form.get("faqs")),related_products:lines(form.get("related_products")),seo:{title:String(form.get("seo_title")||""),description:String(form.get("seo_description")||""),keywords:String(form.get("seo_keywords")||"")},ai_summary:String(form.get("ai_summary")||""),status:String(form.get("status")||"draft"),published_at:String(form.get("published_at")||new Date().toISOString().slice(0,10))};const id=String(form.get("id")||"");const{error}=await(id?s.from("content_entries").update(payload).eq("id",id):s.from("content_entries").insert(payload));if(error)throw error;revalidatePath("/solutions");revalidatePath("/resources");revalidatePath("/faq");redirect("/admin/library")}
export async function deleteContentEntry(id:string){const s=requiredClient();await s.from("content_entries").delete().eq("id",id);revalidatePath("/solutions");revalidatePath("/resources");revalidatePath("/faq")}
export async function saveSetting(key:string,form:FormData){const s=requiredClient();const value:Record<string,string>={};for(const[name,val]of form.entries())if(typeof val==="string")value[name]=val;const{error}=await s.from("site_settings").upsert({key,value});if(error)throw error;revalidatePath("/");redirect("/admin/seo")}
export async function updateInquiryStatus(id:string,form:FormData){const s=requiredClient();await s.from("inquiries").update({status:String(form.get("status")||"new")}).eq("id",id);revalidatePath("/admin/inquiries")}
