"use server";
import{createClient}from"@/lib/supabase/server";import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import type{MediaItem,Spec,QA}from"@/lib/types";

function requiredClient(){const s=createClient();if(!s)throw new Error("Connect Supabase in .env.local first.");return s}
function lines(value:FormDataEntryValue|null){return String(value||"").split("\n").map(x=>x.trim()).filter(Boolean)}
function pairs(value:FormDataEntryValue|null):Spec[]{return lines(value).map(x=>{const[a,...b]=x.split("|");return{label:a.trim(),value:b.join("|").trim()}}).filter(x=>x.label&&x.value)}
function faqs(value:FormDataEntryValue|null):QA[]{return lines(value).map(x=>{const[q,...a]=x.split("|");return{question:q.trim(),answer:a.join("|").trim()}}).filter(x=>x.question&&x.answer)}
function slugify(s:string){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
async function uploadFiles(form:FormData,field="media"){const s=requiredClient();const files=form.getAll(field).filter(x=>x instanceof File&&x.size>0)as File[];const out:MediaItem[]=[];for(const file of files){const ext=file.name.split(".").pop();const path=`${new Date().getFullYear()}/${crypto.randomUUID()}.${ext}`;const{error}=await s.storage.from("media").upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const{data}=s.storage.from("media").getPublicUrl(path);out.push({type:file.type.startsWith("video/")?"video":"image",url:data.publicUrl,alt:file.name})}return out}
function productPayload(form:FormData,media:MediaItem[]){const name=String(form.get("name")||"");return{name,slug:String(form.get("slug")||slugify(name)),category:String(form.get("category")||"Other"),subcategory:String(form.get("subcategory")||""),short_description:String(form.get("short_description")||""),description:String(form.get("description")||""),features:lines(form.get("features")),specifications:pairs(form.get("specifications")),packing_size:pairs(form.get("packing_size")),parts_list:lines(form.get("parts_list")),faqs:faqs(form.get("faqs")),media,youtube_url:String(form.get("youtube_url")||""),moq:String(form.get("moq")||""),featured:form.get("featured")==="on",status:String(form.get("status")||"draft"),sort_order:Number(form.get("sort_order")||0)}}

export async function createProduct(form:FormData){const s=requiredClient();const media=await uploadFiles(form);const{error}=await s.from("products").insert(productPayload(form,media));if(error)throw error;revalidatePath("/products");redirect("/admin/products")}
export async function updateProduct(id:string,existing:MediaItem[],form:FormData){const s=requiredClient();const fresh=await uploadFiles(form);const keep=existing.filter((_,i)=>form.get(`keep_media_${i}`)==="on");const{error}=await s.from("products").update(productPayload(form,[...keep,...fresh].slice(0,8))).eq("id",id);if(error)throw error;revalidatePath("/products");redirect("/admin/products")}
export async function deleteProduct(id:string){const s=requiredClient();await s.from("products").delete().eq("id",id);revalidatePath("/products")}
export async function createCategory(form:FormData){const s=requiredClient();const name=String(form.get("name")||"").trim();if(!name)throw new Error("Category name is required.");const payload={name,slug:String(form.get("slug")||slugify(name)),description:String(form.get("description")||""),sort_order:Number(form.get("sort_order")||0),published:form.get("published")==="on"};const{error}=await s.from("product_categories").insert(payload);if(error)throw error;revalidatePath("/products");revalidatePath("/");redirect("/admin/categories")}
export async function deleteCategory(id:string){const s=requiredClient();const{error}=await s.from("product_categories").delete().eq("id",id);if(error)throw error;revalidatePath("/products");revalidatePath("/")}
export async function savePage(slug:string,existing:MediaItem[],form:FormData){const s=requiredClient();const fresh=await uploadFiles(form);const media=[...existing,...fresh].slice(0,12);const payload={slug,title:String(form.get("title")||slug),eyebrow:String(form.get("eyebrow")||""),heading:String(form.get("heading")||""),body:String(form.get("body")||""),content:{video_url:String(form.get("video_url")||"")},media,published:form.get("published")==="on"};const{error}=await s.from("pages").upsert(payload);if(error)throw error;revalidatePath(`/${slug==="home"?"":slug}`);redirect("/admin/content")}
export async function addGalleryItem(form:FormData){const s=requiredClient();const uploaded=await uploadFiles(form);const media=uploaded[0];if(!media)throw new Error("Choose an image or video.");const collection=String(form.get("collection"));const{error}=await s.from("site_media").insert({collection,title:String(form.get("title")),caption:String(form.get("caption")||""),media_type:media.type,media_url:media.url,link_url:String(form.get("link_url")||""),sort_order:Number(form.get("sort_order")||0),published:form.get("published")==="on"});if(error)throw error;revalidatePath("/");revalidatePath("/scenes");const returnTo=String(form.get("return_to")||"/admin/media");redirect(returnTo.startsWith("/admin/")?returnTo:"/admin/media")}
export async function deleteGalleryItem(id:string){const s=requiredClient();await s.from("site_media").delete().eq("id",id);revalidatePath("/");revalidatePath("/scenes")}
export async function saveNews(form:FormData){const s=requiredClient();const uploaded=await uploadFiles(form,"cover");const title=String(form.get("title")||"");const payload={title,slug:String(form.get("slug")||slugify(title)),excerpt:String(form.get("excerpt")||""),content:String(form.get("content")||""),category:String(form.get("category")||"Company"),cover_url:uploaded[0]?.url||String(form.get("existing_cover")||""),published_at:String(form.get("published_at")||new Date().toISOString().slice(0,10)),status:String(form.get("status")||"draft")};const id=String(form.get("id")||"");const q=id?s.from("news").update(payload).eq("id",id):s.from("news").insert(payload);const{error}=await q;if(error)throw error;revalidatePath("/news");redirect("/admin/news")}
export async function deleteNews(id:string){const s=requiredClient();await s.from("news").delete().eq("id",id);revalidatePath("/news")}
export async function saveQuote(form:FormData){const s=requiredClient();const payload={quote_no:String(form.get("quote_no")),customer:String(form.get("customer")),product:String(form.get("product")),currency:String(form.get("currency")||"USD"),unit_price:Number(form.get("unit_price")||0),moq:Number(form.get("moq")||0),lead_time:String(form.get("lead_time")||""),packing_size:{product_size:String(form.get("product_size")||""),package_size:String(form.get("package_size")||""),net_weight:String(form.get("net_weight")||""),gross_weight:String(form.get("gross_weight")||""),qty_carton:String(form.get("qty_carton")||""),carton_size:String(form.get("carton_size")||""),carton_nw:String(form.get("carton_nw")||""),carton_gw:String(form.get("carton_gw")||""),cbm:String(form.get("cbm")||"")},notes:String(form.get("notes")||"")};const{error}=await s.from("quotes").insert(payload);if(error)throw error;redirect("/admin/quotes")}
