import Link from"next/link";import{Cog,Factory,Globe2,ShieldCheck}from"lucide-react";import{getGallery,getNews,getPage,getProducts}from"@/lib/queries";import ProductCard from"@/components/ProductCard";import SectionHead from"@/components/SectionHead";import GalleryCarousel from"@/components/GalleryCarousel";
export const revalidate=60;
export default async function Home(){const[page,products,news,scenes,customers,logos,hero]=await Promise.all([getPage("home"),getProducts({featured:true}),getNews(3),getGallery("scene"),getGallery("customer"),getGallery("logo"),getGallery("hero")]);const heroMedia=hero[0];const features=[[Cog,"Product Development","Design support, samples and production engineering around your brief."],[Factory,"Factory Direct","An integrated team for manufacturing, inspection and dependable delivery."],[Globe2,"Global Service","Export documentation, logistics and Amazon FBA preparation for key markets."],[ShieldCheck,"Quality Assurance","Defined incoming, in-process and finished-product quality checkpoints."]];return <>
<div className="trust-bar"><div className="container trust-items"><span>14+ Years Experience</span><span>ISO 9001 Certified</span><span>Global B2B Service</span><span>24h Response Time</span><span>OEM / ODM Available</span></div></div>
<section className="hero"><div className="container"><div className="eyebrow">{page?.eyebrow}</div><h1 className="display-title">Illuminate the Future<br/>with <span>Intelligent Light</span></h1><p className="lead">{page?.body}</p><div className="hero-actions"><Link className="btn-primary" href="/products">Explore Products</Link><Link className="btn-secondary" href="/contact">Request Catalog</Link></div>{heroMedia?<div className="media-panel" style={{minHeight:520,marginTop:60}}>{heroMedia.media_type==="video"?<video src={heroMedia.media_url} autoPlay muted loop playsInline/>:<img src={heroMedia.media_url} alt={heroMedia.title}/>}</div>:<div className="light-orb"/>}<div className="stats"><div className="stat"><strong>14+</strong><span>Years Experience</span></div><div className="stat"><strong>3,000</strong><span>Units / Day</span></div><div className="stat"><strong>3,000m²</strong><span>Factory Area</span></div><div className="stat"><strong>20+</strong><span>Markets Served</span></div></div></div></section>
<div className="section-divider"/><section className="section"><div className="container"><SectionHead title="Product" accent="Portfolio" description="Festival, gift, ambient, home and commercial lighting developed for global buyers"/><div className="product-grid">{products.slice(0,3).map(p=><ProductCard key={p.id} product={p}/>)}</div><div style={{textAlign:"center",marginTop:40}}><Link className="btn-secondary" href="/products">View Full Catalog →</Link></div></div></section>
<div className="section-divider"/><section className="section" id="scenes"><div className="container"><SectionHead title="Lighting" accent="Scenes" description="Upload images or videos for every application scene from the admin dashboard"/><div className="scene-grid">{(scenes.length?scenes:["Smart Home","Modern Office","Retail Store","Hotel & Resort","Medical Facility","Warehouse & Factory","School & Campus","Gallery & Museum"].map((title,i)=>({id:String(i),title,caption:"Tailored lighting solutions for this environment.",media_url:"",media_type:"image" as const,collection:"scene" as const,sort_order:i,published:true}))).map(s=><article className="scene-card" key={s.id}>{s.media_url&&(s.media_type==="video"?<video src={s.media_url} muted loop playsInline/>:<img src={s.media_url} alt={s.title}/>)}<div className="scene-overlay"><span className="scene-tag">Application</span><h3>{s.title}</h3><p>{s.caption}</p></div></article>)}</div></div></section>
<div className="section-divider"/><section className="section"><div className="container"><SectionHead title="Why Partner" accent="With Us" description="From prototype to mass production, we deliver reliable support at every stage"/><div className="feature-grid">{features.map(([Icon,title,desc]:any)=><article className="card feature-card" key={title}><div className="feature-icon"><Icon/></div><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<div className="section-divider"/><section className="section"><div className="container"><SectionHead kicker="Partnerships" title="Customers" accent="Worldwide" description="Customer visit photos can be uploaded and reordered in the admin dashboard"/><GalleryCarousel items={customers}/><div style={{height:58}}/><SectionHead kicker="Trusted by" title="Partner" accent="Brands"/><GalleryCarousel items={logos} logos/></div></section>
<div className="section-divider"/><section className="section"><div className="container"><SectionHead title="Latest" accent="News" description="Company updates, product knowledge and industry insights"/><div className="news-grid">{news.map(n=><Link href={`/news/${n.slug}`} className="card" key={n.id}><div className="news-cover">{n.cover_url?<img src={n.cover_url} alt={n.title}/>:<span className="accent" style={{fontSize:42}}>✦</span>}<span className="news-date">{new Date(n.published_at).toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"})}</span></div><div className="news-info"><small>{n.category}</small><h3>{n.title}</h3><p>{n.excerpt}</p></div></Link>)}</div></div></section>
<section className="section" style={{background:"linear-gradient(135deg,#fff1df,#f7d5b6)"}}><div className="container section-head" style={{marginBottom:0}}><div className="kicker">Have a new project?</div><h2>Let’s build your next <span className="accent">lighting product.</span></h2><p>Send your target market, requirements and expected quantity. Our team will respond within 24 hours.</p><div className="hero-actions"><Link href="/contact" className="btn-primary">Start Your Project</Link></div></div></section>
</>}
