import type { GalleryItem, NewsPost, Product, SitePage } from "./types";

export const fallbackProducts: Product[] = [
  { id:"demo-1", slug:"candle-warmer-lamp", name:"Candle Warmer Lamp", category:"Table & Floor Lamps", subcategory:"Candle Warmer Lamps", short_description:"Flameless fragrance lighting with adjustable height, timer and dimming.", description:"A decorative candle warmer engineered for safe, flame-free fragrance and a refined home atmosphere.", features:["Dimmable warm illumination","2H / 4H / 8H timer","Adjustable lamp height","Custom finish and packaging"], specifications:[{label:"Input",value:"100–240V AC 50/60Hz"},{label:"Power",value:"35W"},{label:"Light source",value:"GU10 halogen"},{label:"Materials",value:"Glass, metal and wood"},{label:"Control",value:"Dimmer + timer"},{label:"IP grade",value:"IP20"}], packing_size:[{label:"Product size",value:"Φ15 × H22–30 cm"},{label:"Package size",value:"15 × 15 × 26 cm"},{label:"Net weight",value:"0.9 kg"},{label:"Gross weight",value:"1.0 kg"},{label:"Qty / carton",value:"9 pcs"},{label:"Carton size",value:"48 × 48 × 28 cm"},{label:"Carton N.W.",value:"9.0 kg"},{label:"Carton G.W.",value:"10.5 kg"},{label:"CBM",value:"0.0645 m³"}], parts_list:["1 × Candle warmer lamp","2 × GU10 bulbs","1 × User manual"], faqs:[{question:"Can the finish and packaging be customized?",answer:"Yes. OEM colors, surface finishes, labels, manuals and retail packaging are available."},{question:"Can I order a sample?",answer:"Yes. Contact our sales team with your target market and required plug type."}], media:[], youtube_url:"", moq:"500 pcs", featured:true, status:"published", sort_order:1 },
  { id:"demo-2", slug:"solar-garden-light", name:"Solar Garden Light", category:"Outdoor Lights", subcategory:"Garden LED Lights", short_description:"Automatic IP65 path lighting for gardens, walkways and landscape projects.", description:"A durable solar-powered outdoor light designed for dependable dusk-to-dawn illumination.", features:["Automatic dusk-to-dawn operation","Weather-resistant IP65 housing","High-efficiency solar charging","Tool-free landscape installation"], specifications:[{label:"Light source",value:"High efficiency LED"},{label:"Protection",value:"IP65"},{label:"Control",value:"Auto ON/OFF"},{label:"Application",value:"Garden and pathway"}], packing_size:[], parts_list:["Solar garden light","Ground stake","User guide"], faqs:[{question:"How long does the light operate?",answer:"Runtime depends on solar exposure and battery option. The specification can be configured for your market."}], media:[], moq:"500 pcs", featured:true, status:"published", sort_order:2 },
  { id:"demo-3", slug:"silicone-led-strip", name:"Silicone LED Strip", category:"Tape & String Lights", subcategory:"Silicone Soft Tape Lights", short_description:"Flexible color lighting for retail, interiors, signs and decorative projects.", description:"A smooth, flexible LED lighting system for continuous light effects and easy integration.", features:["Continuous dot-free light","Flexible silicone profile","Multiple CCT and RGB options","Cut lengths and connectors available"], specifications:[{label:"Color options",value:"Single color / CCT / RGB"},{label:"Control",value:"Optional smart controller"},{label:"Installation",value:"Flexible surface mounting"}], packing_size:[], parts_list:["LED strip","Optional controller","Optional power supply"], faqs:[{question:"Can you make custom lengths?",answer:"Yes. Length, connector, voltage, color and packaging can be customized."}], media:[], moq:"200 rolls", featured:true, status:"published", sort_order:3 }
];

export const fallbackNews: NewsPost[] = [
  { id:"n1", slug:"new-lighting-development", title:"New Lighting Development Capabilities for Global Brands", excerpt:"How our team turns a product brief into tested, production-ready lighting.", content:"Our development workflow connects industrial design, electronics, optical testing and manufacturing in one accountable process.", category:"Company", published_at:"2026-08-15", status:"published" },
  { id:"n2", slug:"quality-control-lighting", title:"What Buyers Should Check in a Lighting Quality Plan", excerpt:"A practical overview of incoming, in-process and finished-product inspection.", content:"Reliable lighting starts with clear specifications and repeatable inspection checkpoints.", category:"Quality", published_at:"2026-07-28", status:"published" },
  { id:"n3", slug:"oem-lighting-project", title:"Preparing an OEM Lighting Project for Faster Sampling", excerpt:"The core information that helps shorten the route from idea to approved sample.", content:"Target market, compliance, price point, application, finish and packaging are the best starting inputs.", category:"Guide", published_at:"2026-06-10", status:"published" }
];

export const fallbackPages: Record<string, SitePage> = {
  home:{slug:"home",title:"Home",eyebrow:"Smart Lighting Solutions Since 2011",heading:"Illuminate the Future with Intelligent Light",body:"Shenzhen Xinshern Technology designs and manufactures dependable lighting products for global B2B markets.",content:{},media:[],published:true},
  products:{slug:"products",title:"All Products",eyebrow:"Product Center",heading:"All Products",body:"Browse our complete product range, organized by lighting category.",content:{sections:[{title:"Search by product name, model or category",body:"Search all products"},{title:"No matching products found.",body:"products"}]},media:[],published:true},
  about:{slug:"about",title:"About Xinshern",eyebrow:"Lighting expertise, built over time",heading:"A dependable product partner from Shenzhen",body:"Founded in 2011, Xinshern integrates product development, manufacturing, quality control and export service for festival, gift, ambient and home lighting.",content:{},media:[],published:true},
  factory:{slug:"factory",title:"Factory",eyebrow:"From prototype to mass production",heading:"Manufacturing with accountability",body:"Our production, R&D, inspection and warehousing teams work together to deliver consistent products and reliable lead times.",content:{},media:[],published:true}
};

export const fallbackGallery: GalleryItem[] = [];
